name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Skip on "[skip-ci]"
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
